export const SET_BUN = 'SET_BUN';
export const SET_ITEM = 'SET_ITEM';
export const DROP_ITEM = 'DROP_ITEM';
export const CHANGE_POSITION = 'CHANGE_POSITION';
export const SET_HOVER_POSITION = 'SET_HOVER_POSITION';
export const DROP_HOVER_POSITION = 'DROP_HOVER_POSITION';
export const CLEAR_BASKET = 'CLEAR_BASKET'