export const GET_INGREDIENT = 'GET_INGREDIENT';
export const GET_INGREDIENT_FAILED = 'GET_INGREDIENT_FAILED';
export const GET_INGREDIENT_SUCCESS = 'GET_INGREDIENT_SUCCESS';
export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUNT';
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUNT';