export const GET_CURRENT_ITEM: 'GET_CURRENT_ITEM' = 'GET_CURRENT_ITEM';
export const CLEAR_CURRENT_ITEM: 'CLEAR_CURRENT_ITEM' = 'CLEAR_CURRENT_ITEM';
export const GET_CURRENT_ORDER_NUMBER: 'GET_CURRENT_ORDER_NUMBER' = 'GET_CURRENT_ORDER_NUMBER';
export const CLEAR_CURRENT_ORDER_NUMBER: 'CLEAR_CURRENT_ORDER_NUMBER' = 'CLEAR_CURRENT_ORDER_NUMBER';
