export const GET_LOGIN_INFO: 'GET_LOGIN_INFO' = 'GET_LOGIN_INFO'
export const GET_LOGIN_INFO_SUCCESS: 'GET_LOGIN_INFO_SUCCESS' = 'GET_LOGIN_INFO_SUCCESS'
export const GET_LOGIN_INFO_FAILED: 'GET_LOGIN_INFO_FAILED' = 'GET_LOGIN_INFO_FAILED'

export const GET_REGISTRATION_INFO: 'GET_REGISTRATION_INFO' = 'GET_REGISTRATION_INFO'
export const GET_REGISTRATION_INFO_SUCCESS: 'GET_REGISTRATION_INFO_SUCCESS' = 'GET_REGISTRATION_INFO_SUCCESS'
export const GET_REGISTRATION_INFO_FAILED: 'GET_REGISTRATION_INFO_FAILED' = 'GET_REGISTRATION_INFO_FAILED'

export const GET_LOGOUT_INFO: 'GET_LOGOUT_INFO' = 'GET_LOGOUT_INFO'
export const GET_LOGOUT_INFO_SUCCESS: 'GET_LOGOUT_INFO_SUCCESS' = 'GET_LOGOUT_INFO_SUCCESS'
export const GET_LOGOUT_INFO_FAILED: 'GET_LOGOUT_INFO_FAILED' = 'GET_LOGOUT_INFO_FAILED'

export const GET_USER_INFO: 'GET_USER_INFO' = 'GET_USER_INFO'
export const GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS' = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED' = 'GET_USER_INFO_FAILED'

export const CHANGE_USER_INFO: 'CHANGE_USER_INFO' = 'CHANGE_USER_INFO'
export const CHANGE_USER_INFO_SUCCESS: 'CHANGE_USER_INFO_SUCCESS' = 'CHANGE_USER_INFO_SUCCESS'
export const CHANGE_USER_INFO_FAILED: 'CHANGE_USER_INFO_FAILED' = 'CHANGE_USER_INFO_FAILED'